spring:
  datasource:
    url: jdbc:h2:mem:checkpoint
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

app:
  security:
    allowed-origins: http://localhost:4209
    jwt-expiration-time-minutes: 720  # 12 hours in minutes
    jwt-signature-secret-base64-key: dGhpc2lzZW5jb2RlZHNjb29ieWRvb2J5ZG9vb29vb29vdGhpc2lzZW5jb2RlZA==

logging:
  level:
    org:
      springframework:
        security: DEBUG
