spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017
      database: checkpoint

app:
  security:
    allowed-origins: http://localhost:4209
    jwt-expiration-time-minutes: 720  # 12 hours in minutes
    jwt-signature-secret-base64-key: dGhpc2lzZW5jb2RlZHNjb29ieWRvb2J5ZG9vb29vb29vdGhpc2lzZW5jb2RlZA==

logging:
  level:
    org:
      springframework:
        security: DEBUG
