spring:
  datasource:
    url: jdbc:h2:mem:checkpoint
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  spring:
    h2:
      console.enabled: true

app:
  security:
    allowed-origins: http://localhost:4209
    jwt-expiration-time-seconds: 43200  # 12 hours in seconds
    jwt-signature-secret-base64-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

logging:
  level:
    org:
      springframework:
        security: DEBUG
